version: '3.8'

services:
  resume-analyzer-backend:
    build: .
    container_name: resume-analyzer-backend
    ports:
      - "8000:8000"
    volumes:
      - ./config.env:/app/config.env
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
  resume-analyzer-frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - VUE_APP_API_URL=http://localhost:8000
    depends_on:
      - resume-analyzer-backend

  # nginx:
  #   image: nginx:alpine
  #   container_name: resume-analyzer-nginx
  #   ports:
  #     - "8001:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #     - ./index.html:/usr/share/nginx/html/index.html
  #     - ./report.html:/usr/share/nginx/html/report.html
  #   depends_on:
  #     - resume-analyzer-backend
  #     - resume-analyzer-frontend
  #   restart: unless-stopped 