version: '3.8'

services:
  resume-analyzer:
    build: .
    container_name: resume-analyzer
    ports:
      - "8000:8000"
    volumes:
      - ./config.env:/app/config.env
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped 