version: '3.8'

services:
  resume-analyzer:
    build: .
    container_name: resume-analyzer
    ports:
      - "8000:8000"
    volumes:
      - ./config.env:/app/config.env
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: resume-analyzer-nginx
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./index.html:/usr/share/nginx/html/index.html
      - ./report.html:/usr/share/nginx/html/report.html
    depends_on:
      - resume-analyzer
    restart: unless-stopped 